### ISSUE TITLE
Issue with forward_pass.sh

### ISSUE THREAD

**Issue by matthewchung74** [obi-ml-public/ehr_deidentification#6]
seeing another issue where `forward_pass.sh` gives errors. this is on 
ubuntu 20.04
python 3.7.9
where pip install was used as the following
pip install -r ehr_deidentification/requirements.txt #removed typing and tensor flow references
pip install robust-deid

I saw online there are fixes for this, but that requires upgrading spacy, which breaks other dependencies. Any suggestions are appreciated.

```
(venv) matt@ip-10-3-3-249:~/ehr_deidentification/steps/forward_pass$ sh forward_pass.sh 
Traceback (most recent call last):
  File "/mnt/disk/matt/venv/bin/create_data", line 5, in <module>
    from robust_deid.ner_datasets.dataset_creator import main
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/ner_datasets/__init__.py", line 1, in <module>
    from .span_fixer import SpanFixer
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/ner_datasets/span_fixer.py", line 6, in <module>
    from .preprocessing import PreprocessingLoader
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/ner_datasets/preprocessing/__init__.py", line 1, in <module>
    from .preprocessing_loader import PreprocessingLoader
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/ner_datasets/preprocessing/preprocessing_loader.py", line 3, in <module>
    from .sentencizers import SpacySentencizer, NoteSentencizer
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/ner_datasets/preprocessing/sentencizers/__init__.py", line 2, in <module>
    from .spacy_sentencizer import SpacySentencizer
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/ner_datasets/preprocessing/sentencizers/spacy_sentencizer.py", line 3, in <module>
    import spacy
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/mnt/disk/matt/venv/lib/python3.7/site-packages/click/termui.py)
Traceback (most recent call last):
  File "/mnt/disk/matt/venv/bin/tag_sequence", line 5, in <module>
    from robust_deid.sequence_tagging.sequence_tagger import main
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/__init__.py", line 1, in <module>
    from .sequence_tagger import SequenceTagger
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/sequence_tagger.py", line 33, in <module>
    from .models.hf import ModelPicker
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/models/hf/__init__.py", line 1, in <module>
    from .model_picker import ModelPicker
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/models/hf/model_picker.py", line 6, in <module>
    from .crf.utils import allowed_transitions
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/models/hf/crf/__init__.py", line 1, in <module>
    from .crf_bert_model_for_token_classification import CRFBertModelForTokenClassification
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/models/hf/crf/crf_bert_model_for_token_classification.py", line 6, in <module>
    from .conditional_random_field_sub import ConditionalRandomFieldSub
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/robust_deid/sequence_tagging/models/hf/crf/conditional_random_field_sub.py", line 4, in <module>
    from allennlp.modules import ConditionalRandomField
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/allennlp/__init__.py", line 18, in <module>
    import transformers, spacy, torch, numpy  # noqa
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/mnt/disk/matt/venv/lib/python3.7/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/mnt/disk/matt/venv/lib/python3.7/site-packages/click/termui.py)
```

**Comment by prajwal967** [comment]
Were you able to fix this?

**Comment by matthewchung74** [comment]
Kind of, yes, the Conda installation worked fine.
